### ISSUE TITLE
Outputting extra line returns

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/asconfigc#13]
When running asconfigc, I'm seeing a lot of extra line returns which causes the results to scroll up off the screen.
https://github.com/BowlerHatLLC/vscode-nextgenas/issues/109

**Comment by Harbs** [comment]
Could this be it?
https://github.com/BowlerHatLLC/asconfigc/blob/9b4d3b9b31233529e1d47a8b56becab18043da39/src/com/nextgenactionscript/asconfigc/utils/assetPathToOutputPath.as#L46

**Comment by joshtynjala** [comment]
Good catch! That's probably it. I had noticed some extra lines recently too, and I assumed it was just some weird quirk of VSCode's Terminal panel. I'll bet that VSCode was stripping those extra lines when they were displayed in the Output panel (so we didn't notice), but it doesn't strip them in the Terminal panel.

**Comment by joshtynjala** [comment]
This issue is fixed in today's v0.5.2 update to asconfigc.

**Comment by Harbs** [comment]
Installed and tested. Perfect! :heart:

**Comment by Harbs** [comment]
(BTW, I don't see a commit to the above file. Was it that or something else?)

**Comment by joshtynjala** [comment]
That was it! I just forgot to push the master branch.
