### ISSUE TITLE
application.xml fwritesync

### ISSUE THREAD

**Issue by celeryness** [BowlerHatLLC/asconfigc#17]
Can I just say first Josh thanks very much for all the great work here...

I am working on an air-mobile project that I am trying to port to FlexJS (using 0.8.0 - I will switch to Royale when its official). I was getting a failure when trying to build, is seems that there is call to fwritesync after compiling the FlexJS output, that wants to make a copy of the AIR descriptor xml file, but is pointing to a bin/bin/js-debug and not bin/js-debug and that causes a crash in the build:

**Error: ENOENT: no such file or directory, open '/Volumes/LocalData/Users/mick/flex-projects/MobileStocks/MobileStocks/bin/bin/js-debug/MobileStocks-app.xml'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.writeFileSync (fs.js:1314:33)**

It may well be due to my setup, and I have been trying to follow your instructions and use the sample MobileStocks app rather than my own as a test, but I still get the same error. I made a folder called MobileStocks and then copied the MobileStocks example into that. My workaround is just to copy the air descriptor xml file into a bin/js-debug folder in the bin folder.
My asconfig.json is:

``` json
{
    "config": "airmobile",
	"compilerOptions": {
		"output": "MobileStocks/bin/MobileStocks.swf"
    },
    "application": "MobileStocks/MobileStocks-app.xml",
	"files":
	[
		"MobileStocks/src/main/flex/MobileStocks.mxml"
	]
}
```

tasks.json is:
``` json
{
	"version": "2.0.0",
	"tasks": [
		{
			"identifier": "build-debug",	
			"type": "actionscript",
			"debug": true,
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

**Comment by joshtynjala** [comment]
Try changing your *asconfig.json* file like this:

``` json
{
	"config": "airmobile",
	"compilerOptions": {
		"targets": [
			"JSFlex"
		],
		"output": "MobileStocks"
	},
	"application": "MobileStocks/MobileStocks-app.xml",
	"files":
	[
		"MobileStocks/src/main/flex/MobileStocks.mxml"
	]
}
```

Right now, you have it set to build both SWF and JS output, and this should make it JS only.

**Comment by celeryness** [comment]
That didn't quite do the job for me, as I still get an error:

Error: ENOENT: no such file or directory, open '/Volumes/LocalData/Users/mick/flex-projects/MobileStocks/bin/js-debug/MobileStocks-app.xml'

I wondered if it was a permissions issue with node as I'm working on a mac and it can get a bit screwy with node and npm sometimes, but I went out into the terminal and ran asconfigc manually as sudo and I still get the same error. I have also closed and reopened vscode as well but no joy. My original workaround of copying the descriptor file into the destination folder doesn't seem to work either now which is pretty strange. I have gone back to my original workaround and config as I can get that to work.

**Comment by joshtynjala** [comment]
You might also try making the *MobileStocks* directory the root of your workspace and moving *asconfig.json* there.

``` json
{
	"config": "airmobile",
	"compilerOptions": {
		"targets": [
			"JSFlex"
		],
		"output": "."
	},
	"application": "MobileStocks-app.xml",
	"files":
	[
		"src/main/flex/MobileStocks.mxml"
	]
}
```

It could certainly be that there's a bug where moving everything down a subdirectory doesn't work for some reason. Or maybe it's because you're using the "airmobile" config value. I have literally never actually tried to build a FlexJS/Royale project that targets Adobe AIR. Since AIR's support for HTML/JS/CSS isn't that great, I'm not sure it's worth pursuing that direction.

**Comment by celeryness** [comment]
I had to get back to the "day job" - sorry I didn't reply so quickly to your last comment. My actual intention is to go out to air mobile still using flex/actionscript (but with the FlexJS libraries/components), while having a potential fall-back JS version that I could use for Cordova.

I did what you suggested and you are right in that there seems to be a restriction that the directory is structured a certain way - maybe that's the compiler itself that's expecting that? I know some of the history and I've been on the Flex mailing lists since the move to Apache so I'm not surprised that there are some limitations to folder structures, and some of that probably comes from the FB days. I have some ant tasks that I've been using for years with FlashDevelop - but as I'm moving over to vscode I wanted to give asconfigc a go. If I get time I'll pull your repo and see if I can hack a solution.

I went back to your original suggestion/configuration, and for anyone reading this - that works with the expected folder structure, and I just added an extra target for "SWF". One thing though was the output SWF ended up in a slightly weird place: 

**185562 bytes written to /Volumes/LocalData/Users/mick/flex-projects/MobileStocks/src/main/flex/MobileStocks.swf** 

Cheers Josh

**Comment by joshtynjala** [comment]
> One thing though was the output SWF ended up in a slightly weird place:

If you don't specify an output path, the compiler creates the SWF in the same directory as your project's main class. I wish it were the current working directory instead, but when I mentioned the possibility of changing it, at least one major/influential Apache contributor was strongly opposed because it would disrupt his established workflow he'd been using for years. It didn't seem worth arguing over.
