### ISSUE TITLE
Constant bad formating

### ISSUE THREAD

**Issue by Incubatio** [BowlerHatLLC/asconfigc#18]
Currently string constants are not generated properly, which will lead to the compilation error:
_col: 95 Error: The initializer for a configuration value must be a compile time constant._

in asconfig:
```
        "define": [
          { "name": "CONFIG::DEBUG_NS", "value": "*" }
       ]
```
generated line:
```bash
--define+=CONFIG::DEBUG_NS,*
```
Double or single quote have to be used(1), what it should look like:
```bash
--define+=CONFIG::DEBUG_NS,"*"
```
even using additionalOptions will trim double quote and single quote out:
```
   "additionalOptions": "--define+=CONFIG::DEBUG_NS,\"*\""
```

(1) "Using conditional compilation" in https://help.adobe.com/archive/en_US/flex/using/flex_4.6_help.pdf

**Comment by joshtynjala** [comment]
As I recall, you need to add another layer of quotes to define strings. I think this will work:

``` json
{ "name": "CONFIG::DEBUG_NS", "value": "\"*\"" }
```

I seem to remember that the compiler allows you to define non-string basic expressions (like "1+2", for instance) with quotes, so that's why you need to wrap strings with an extra set of quotes.

**Comment by Incubatio** [comment]
I already tried it.
Quote and double quote get trimmed out.

**Comment by joshtynjala** [comment]
Hmmm... perhaps I misremembered. It looks like escaped strings don't work well. I just tested, and you can use single quotes on the inner string instead:

``` json
{ "name": "CONFIG::DEBUG_NS", "value": "'*'" }
```

**Comment by Incubatio** [comment]
Ok I kept having the issue, but I updated my node version.
Now i can use quote and double quote, my bad.
Thanks for the the answer.

**Comment by joshtynjala** [comment]
Interesting! Which Node version did you have installed before?

**Comment by Incubatio** [comment]
node/6.11.0

**Comment by joshtynjala** [comment]
Thanks!

**Comment by Incubatio** [comment]
I just tried to reproduce by re-switching to node/6.11.0, but I can't ...
Probably a bug related to a npm dependancy, or to a local problem -_-.

**Comment by joshtynjala** [comment]
👹 Gremlins! Haha.
