### ISSUE TITLE
Override output from command line

### ISSUE THREAD

**Issue by vrokolos** [BowlerHatLLC/asconfigc#21]
Can we have an -output switch so that it ignores the one from asconfig.json and uses this instead?

**Comment by joshtynjala** [comment]
I took a different approach, but this is now supported.

The new [`extends`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#extends) field in _asconfig.json_ allows you to reference a base _asconfig_ file and override anything that you want.

_asconfig.json_

```json
{
	"compilerOptions": {
		"output": "bin/MyProject.swf"
	},
	"files": [
		"src/MyProject.as"
	]
}
```

_asconfig.custom.json_

```json
{
	"extends": "asconfig.json",
	"compilerOptions": {
		"output": "bin/Custom.swf"
	}
}
```

You can replace the middle section of the file name with anything. It has to start with _asconfig._ and end with _.json_.

Command line usage:

```
asconfigc --project asconfig.custom.json
```

In VSCode, all _asconfig.*json_ files are detected in the workspace root, and they are each given their own set of build tasks.
