### ISSUE TITLE
Inconsistencies with airOptions->files between debug and build

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/asconfigc#24]
I have separated embedded and non-embedded assets in my project, so that I can avoid embedded assets being copied to the release build. I don't want to enable copySourcePathAssets as there are a lot of assets I don't want copied over.

Please see this basic project example, which exhibits the issue: https://www.dropbox.com/s/0q1ny9os8y3x2tm/asconfigc%20Files%20Issue.zip?dl=0

In bin-release, the folder is correctly copied to assets/images/, but in bin-debug it's copied to images/ - the assets parent folder is somehow ignored.

**Comment by joshtynjala** [comment]
Thanks, I'll take a look!
