### ISSUE TITLE
Readme update, or added functionality, for jvmargs support.

### ISSUE THREAD

**Issue by Zageron** [BowlerHatLLC/asconfigc#27]
Ran into an issue where embedding fonts into a swc failed because the JVM ran out of memory.

Solution:
`asconfigc.cmd '--sdk', 'c:\airsdk\32.0.0.116', '--debug=false', '--project', '.\font\asconfig.embed-fonts.json' '--jvmargs=-Xmx1000m'`

Couldn't figure out any other way to do it other than calling this manually. Would be awesome to have either the default maximum of the JVM just increased, since it doesn't matter, or adding a configurable option to increase it.

Thanks!

**Comment by joshtynjala** [comment]
> or adding a configurable option to increase it.

@Zageron Isn't that what you're using here?

> --jvmargs=-Xmx1000m

This option is indeed how you specify custom JVM args when running asconfigc.

Or maybe you're talking about customizing asconfigc when launched from VSCode? In that case, you can use `as3mxml.asconfigc.jvmargs` in VSCode's settings.
