### ISSUE TITLE
Doc request: Mention that asconfigc itself is written in ActionScript and transpiled with FlexJS to JS/Node

### ISSUE THREAD

**Issue by olafkrueger** [BowlerHatLLC/asconfigc#9]
Hi Josh,
probably it's obvious for some people but I think it is worth to mention in the readme that asconfigc itself is transpiled to JS/Node by using Falcon and also captures packages like jsen and minimist. 

So this is a real world example for an awesome working AS3/JS app! ;-)

Although I spend some time with FlexJS it took some time until I noticed that *lol

Thanks,
Olaf

**Comment by joshtynjala** [comment]
That's a good idea!
